# -*- coding: utf-8 -*-
MAP4A = [
 ("w.dash.title","Worker Dashboard","WNQJGNOFK NLBPLHVFYQ"),
 ("w.dash.my.orders","My Assigned Orders","VDJ NJUKTKAGHOJ CACGTPNZ"),
 ("w.dash.progress","Today's Progress","RZZUOX MW LGBOZVPXE"),
 ("w.dash.tasks.completed","Tasks Completed","TVXBOD VAOTWCGX"),
 ("w.dash.pending.tasks","Pending Tasks","VZYVCJE WATHGBB"),
 ("w.dash.stock.updated","Stock Updated (units)","JEFJDFZV WUUALCYO (SQFSPDEX)"),
 ("w.dash.update.stock","Update Stock","SPBTKLC XOQJIKR"),
 ("w.dash.update.desc","Record newly produced fabrics.","TUMDMHS VDPJHKPG QIPRTUNRD XJXLY."),
 ("w.dash.my.tasks","My Tasks","FAO GHOMDGP"),
 ("w.dash.my.tasks.desc","View assigned work and update status.","XWJAQNDQCB CIXNKAZ GVZZB UZJQLSO."),
 ("w.dash.view.tasks","View Tasks","WGRVSGUT HAGQJ"),
 ("w.dash.my.profile","My Profile","HIN OZDGOLYC"),
 ("w.dash.my.profile.desc","Manage your profile information.","PNDHPM EGIYM ZVSMEMMZ CFKRS."),
 ("w.dash.open.profile","Open Profile","MWAGDPTRRG QVCEJ"),
 ("w.dash.no.orders","No orders assigned yet.","LJZSR REWAIKWH OQTLVOAAXEJ QDSTD."),
 ("w.orders.title","Worker Orders","YAFHQEOR LVMLNVG"),
 ("w.orders.sub","View and update your assigned orders.","UHJEMVMRPI MNZEIYGFH YJADHZDT."),
 ("w.orders.assigned","Assigned Orders","QKTJTJBVZ KQVVJKQX"),
 ("w.mytasks.title","My Assigned Tasks","BWOWM XBXPCPZIR FUQIYZN"),
 ("w.mytasks.sub","Track and update your task progress.","PYRCC YJAOHW YRNAA OXJDIIYFJKP."),
 ("w.mytasks.list","Task List","ACXS FKOGQR"),
 ("w.mytasks.empty","No tasks assigned to you yet.","ZNMZTTEM ZBGHC DUTBK AVUSNNIDUOWAWYZ."),
 ("w.notif.sub","Alerts about tasks, orders and payments.","RFIQWEW, HCPDQGWE, SJBKXXGIGEBV WQHJYD."),
 ("w.pay.sub","Payments recorded for your completed work.","BJFYPG CZEHDJ RXONOQCAGLM PAFO."),
 ("w.pay.jobs","Completed Jobs","HZIMRLC NNOQZBIJG"),
 ("w.pay.qty","Total Quantity","SQBVKX XFJOF"),
 ("w.pay.earned","Total Earned (Paid)","XEUHJT ZGYZDTG (QJNKJSHBQGQOUS)"),
 ("w.pay.my","My Payments","RHP TYMOLLMQFOGW"),
 ("w.pay.empty","No payments recorded yet.","ULMJGTATPGSTO XZXYOAP FVBTX WJDA."),
 ("w.stock.title","Stock Inventory","XTHSQA QFXWPWZ"),
]
