# -*- coding: utf-8 -*-
MAP4C = [
 ("a.dash.card.approval","User Approval","MBPZV QWSJRCTP"),
 ("a.dash.card.approval.desc","Review and approve pending registrations.","UMEFIMCV TWZE EZVMYQYIR GQD ZNOVO."),
 ("a.dash.card.logs","Activity Logs","ZANKCNMZUETK YYGHFKPSH"),
 ("a.dash.card.logs.desc","Audit important actions across the system.","EBLWONXIG IBVI JWCZVGJHLC OBWQYDTL."),
 ("a.dash.card.notif","Notifications","IZNBPNVJXCWD"),
 ("a.dash.card.notif.desc","View and manage system notifications.","ELFQMR OQOGCNIGB KEAVKMMHCM GNSG."),
 ("a.dash.welcome","Welcome back,","TUAKBM SJQWATLKHFO,"),
 ("th.product","Product","JPEBZSAGH"),
 ("th.quantity","Quantity","KBVZ"),
 ("th.worker","Worker","VVIWXMIBD"),
 ("th.request.date","Request Date","QXTSESRBY SNWI"),
 ("th.delivery.date","Delivery Date","YLKVZYLSI YWGF"),
 ("th.status","Status","XSVX"),
 ("th.remarks","Remarks","LVAIVTEPZY"),
 ("th.product.name","Product Name","CFVYGWXTF SMXRU"),
 ("th.category","Category","HYEE"),
 ("th.location","Location","CNCS"),
 ("th.action","Action","DMWN"),
 ("th.order.id","Order ID","CFWGX FQV"),
 ("th.payment.id","Payment ID","PVEXYTDLO JPW"),
 ("th.order.lbl","Order","PONOC"),
 ("th.amount","Amount","XACAQ"),
 ("th.date","Date","KDIF"),
 ("th.task.id","Task ID","UVAJ BIT"),
 ("th.task.name","Task Name","GVTC LBRK"),
 ("th.department","Department","YFCMC"),
 ("th.due.date","Due Date","KHMJ BCDE"),
 ("th.completed.status","Completed Status","QPGLKYQ JYCX"),
 ("th.owner","Owner","QYPEVWOQGXFS"),
 ("th.process.stage","Process Stage","VNXZNZG YTFE"),
 ("th.assigned.worker","Assigned Worker","YQOLJGQEFE HQPFVPRRM"),
 ("th.actions","Actions","IEIEWHKTF"),
 ("th.qty","Qty","KGNI"),
]
