# -*- coding: utf-8 -*-
MAP4B = [
 ("w.stock.sub","View and manage your stock entries.","JFGLTR UAPJJH KXOOLGKRK CGKE."),
 ("w.stock.total","Total Items","EZFISR DLSVJWBBP"),
 ("w.stock.my","My Stock Entries","IEH PHVQZU NNILKFGC"),
 ("w.add.title","Add New Stock","FWZUW VZPCBJ ZSTBL"),
 ("w.add.sub","Add raw materials to inventory.","SXWGLKOAWMKZQT CXYMA MYGAGD."),
 ("w.add.info","Stock Information","SOYVGA FQBKUGK"),
 ("w.add.product","Product Name","RGRFLYWPY KJJXL"),
 ("w.add.category","Category","BLMP"),
 ("w.add.select.cat","Select Category","XYQBJM QASPG DIIGF CMWT"),
 ("w.add.qty","Quantity","LYYY"),
 ("w.add.location","Location / Warehouse","LMBW / NWUHRPJ"),
 ("w.add.submit","Add Stock","QGVHRN KUPO"),
 ("w.hist.title","Work History","PLQE HDCQSLK"),
 ("w.hist.sub","All work you have completed.","BBQBGI AILMFQ KPYOIOB AZLWCDDC."),
 ("w.hist.completed.work","Completed Work","CGSWYRR TIRXG"),
 ("w.hist.empty","No completed work yet.","OAOOD YUPQHHW NFNVMW IVTSVF OVREM."),
 ("w.hist.completed.of","Completed","VYVUHAHY"),
 ("w.hist.total","Total","LGEOOE"),
 ("a.dash.title","Admin Dashboard","XYPBO HECDGJQHH"),
 ("a.dash.review","Review Users","ZREHFWKJ LNVMJQYLOCZ"),
 ("a.dash.total.users","Total Users","LHCHVN AZXBGBGMPK"),
 ("a.dash.total.owners","Total Owners","KUBTXM ISNKODKGIGW"),
 ("a.dash.total.workers","Total Workers","IKPKWS RPORIQBRXNJ"),
 ("a.dash.pending","Pending Approvals","ZMPIPANM VBHGSMWCXVS"),
 ("a.dash.overview","System Overview","NSMFNPM JUUIDWUTUX"),
 ("a.dash.summary","Quick Summary","EBFYDB LXYOMMBA"),
 ("a.dash.total.tasks","Total Tasks","RBUNQD SGREBZXQ"),
 ("a.dash.completed.tasks","Completed Tasks","GMQUSIJ EQZIYYZ"),
 ("a.dash.unread","Unread Notifications","YTTZQJGFVMV RGIPFGGRIBGI"),
 ("a.dash.recent.reg","Recent Registrations","SGVKBCVEW EZXTVLQFJRW"),
 ("a.dash.no.reg","No registrations yet.","YMLGCO UJSFRLXDSUS QVOIZI UYFXQ."),
 ("a.dash.recent.act","Recent Activity","WJTPXEBBY JXNKYGBVQN"),
 ("a.dash.no.act","No activity recorded yet.","DUVNKT XNTXOEG CJPNSY CVRTYY DVXOE."),
]
