package com.textile.smart_textile_tracking_system.service;

import com.textile.smart_textile_tracking_system.entity.Report;
import com.textile.smart_textile_tracking_system.repository.ReportRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class ReportService {

    @Autowired
    private ReportRepository reportRepository;

    // Save Report
    public Report saveReport(Report report) {
        return reportRepository.save(report);
    }

    // Get All Reports
    public List<Report> getAllReports() {
        return reportRepository.findAll();
    }

    // Get Report By ID
    public Optional<Report> getReportById(Long id) {
        return reportRepository.findById(id);
    }

    // Get Reports By Type
    public List<Report> getReportsByType(String reportType) {
        return reportRepository.findByReportType(reportType);
    }

    // Get Reports By Generated By
    public List<Report> getReportsByGeneratedBy(String generatedBy) {
        return reportRepository.findByGeneratedBy(generatedBy);
    }

    // Delete Report
    public void deleteReport(Long id) {
        reportRepository.deleteById(id);
    }
}